const actionTypesTodo = {
  SET_TODOS: "SET_TODOS",
  GET_ALL_TODOS: "GET_ALL_TODOS",
  CREATE_TODOS: "CREATE_TODOS",
  GET_MORE_TODOS: "GET_MORE_TODOS",
  HES_MORE_TODO: "HES_MORE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
};

export default actionTypesTodo;
