export const actionTypes = {
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  SET_POSTS: "SET_POSTS",
  GET_MORE_POSTS: "GET_MORE_POSTS",
  UPDATE_POSTS: "UPDATE_POSTS",
  CREATE_POSTS: "CREATE_POSTS",
  GET_ALL_POSTS: "GET_ALL_POSTS",
};

// now < 1616184000000 fb
// now < 1616184000000
